// CELLAR — curated pick lists for the manual form's comboboxes.
// GENERATED from content/cellar-lists.csv by scraps/mirror-cellar-lists.js —
// do not hand-edit; refine rows in the CSV and re-run the mirror.
// Vintages are derived at runtime (current year → 1940 + NV) — see
// cellarVintages() in cellar-store.js.

const CELLAR_LISTS = {
  types: ["Red", "White", "Rosé", "Sparkling", "Orange", "Fortified", "Dessert"],
  countries: ["Argentina", "Australia", "Austria", "Brazil", "Bulgaria", "Canada", "Chile", "China", "Croatia", "England", "France", "Georgia", "Germany", "Greece", "Hungary", "Israel", "Italy", "Japan", "Lebanon", "Mexico", "Moldova", "Morocco", "New Zealand", "Portugal", "Romania", "Slovenia", "South Africa", "Spain", "Switzerland", "Turkey", "Uruguay", "USA"],
  grapes: [
    "Aglianico",
    "Airén",
    "Albariño",
    "Aligoté",
    "Arneis",
    "Assyrtiko",
    "Barbera",
    "Blaufränkisch",
    "Bobal",
    "Bonarda",
    "Cabernet Franc",
    "Cabernet Sauvignon",
    "Carignan",
    "Cariñena",
    "Carmenère",
    "Catarratto",
    "Chardonnay",
    "Chasselas",
    "Chenin Blanc",
    "Cinsault",
    "Clairette",
    "Colombard",
    "Cortese",
    "Corvina",
    "Counoise",
    "Dolcetto",
    "Dornfelder",
    "Falanghina",
    "Fernão Pires",
    "Fiano",
    "Frappato",
    "Friulano",
    "Furmint",
    "Gamay",
    "Garganega",
    "Garnacha",
    "Garnacha Blanca",
    "Gewürztraminer",
    "Glera",
    "Godello",
    "Graciano",
    "Grechetto",
    "Greco",
    "Grenache",
    "Grenache Blanc",
    "Grillo",
    "Grolleau",
    "Grüner Veltliner",
    "Hárslevelű",
    "Hondarrabi Zuri",
    "Kadarka",
    "Kékfrankos",
    "Kerner",
    "Lagrein",
    "Lambrusco",
    "Listán Negro",
    "Loureiro",
    "Macabeo",
    "Malbec",
    "Malvasia",
    "Marsanne",
    "Marselan",
    "Mataro",
    "Mavrud",
    "Melon de Bourgogne",
    "Mencía",
    "Merlot",
    "Monastrell",
    "Mondeuse",
    "Montepulciano",
    "Moschofilero",
    "Mourvèdre",
    "Müller-Thurgau",
    "Muscadelle",
    "Muscat",
    "Muscat Blanc à Petits Grains",
    "Nebbiolo",
    "Negroamaro",
    "Nerello Mascalese",
    "Nero d'Avola",
    "Nero di Troia",
    "Palomino",
    "Parellada",
    "Pecorino",
    "Pedro Ximénez",
    "Petit Manseng",
    "Petit Verdot",
    "Petite Sirah",
    "Picpoul",
    "Pinot Blanc",
    "Pinot Grigio",
    "Pinot Gris",
    "Pinot Meunier",
    "Pinot Noir",
    "Pinotage",
    "Plavac Mali",
    "Poulsard",
    "Primitivo",
    "Prosecco",
    "Refosco",
    "Ribolla Gialla",
    "Riesling",
    "Rkatsiteli",
    "Roussanne",
    "Sagrantino",
    "Sangiovese",
    "Saperavi",
    "Sauvignon Blanc",
    "Savagnin",
    "Schiava",
    "Sémillon",
    "Sercial",
    "Seyval Blanc",
    "Shiraz",
    "Silvaner",
    "Syrah",
    "Tannat",
    "Tempranillo",
    "Teroldego",
    "Timorasso",
    "Tinta Barroca",
    "Tinta Roriz",
    "Torrontés",
    "Touriga Franca",
    "Touriga Nacional",
    "Trebbiano",
    "Trepat",
    "Trousseau",
    "Trousseau Gris",
    "Ugni Blanc",
    "Valdiguié",
    "Verdejo",
    "Verdicchio",
    "Vermentino",
    "Vernaccia",
    "Viognier",
    "Viura",
    "Welschriesling",
    "Xarel·lo",
    "Xinomavro",
    "Zibibbo",
    "Zinfandel",
    "Zweigelt",
  ],
};

if (typeof window !== "undefined") { window.CELLAR_LISTS = CELLAR_LISTS; }
